name: assignment16
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=8.22.2
  - matplotlib=3.8.4
  - nbconvert=7.16.3
  - numpy=1.26.4
  - python=3.10.14
  - pip:
    - opencv-python==4.9.0.80
